language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nicholasjdefina/docker-react-testing -f Dockerfile.dev .

script:
  - docker run -e CI=true nicholasjdefina/docker-react-testing npm run test